# # HEWAN data
# # HEWAN data
# hewan_data = [
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
#         'nama': 'Raja',
#         'spesies': 'Panthera tigris sumatrae',
#         'asal_hewan': 'Sumatera, Indonesia',
#         'tanggal_lahir': '2018-03-12',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Hutan Hujan Tropis',
#         'url_foto': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdBHMhY_ICwg4ta5lg9JkF0ADznhYlJbt0JA&s',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12',
#         'nama': 'Kiko',
#         'spesies': 'Pongo pygmaeus',
#         'asal_hewan': 'Kalimantan, Indonesia',
#         'tanggal_lahir': '2016-07-23',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Hutan Hujan Tropis',
#         'url_foto': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTu_8lN2BoofoWQgpYfVt5XvQqPoGyiqRqvxA&s',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13',
#         'nama': 'Luna',
#         'spesies': 'Elephas maximus sumatranus',
#         'asal_hewan': 'Sumatera, Indonesia',
#         'tanggal_lahir': '2014-05-17',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Hutan Hujan Tropis',
#         'url_foto': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRm-beLgPGJKth2krKGtsKVyUniV5FuzevuVA&s',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a14',
#         'nama': 'Simba',
#         'spesies': 'Panthera leo',
#         'asal_hewan': 'Tanzania, Afrika',
#         'tanggal_lahir': '2019-01-28',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Savana',
#         'url_foto': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Lion_waiting_in_Namibia.jpg/1200px-Lion_waiting_in_Namibia.jpg',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a15',
#         'nama': 'Bolt',
#         'spesies': 'Acinonyx jubatus',
#         'asal_hewan': 'Kenya, Afrika',
#         'tanggal_lahir': '2020-04-05',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Savana',
#         'url_foto': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDK5pfJ34gxt_6SVC1rgdyCChW2mriEjiLeA&s',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a16',
#         'nama': 'Miko',
#         'spesies': 'Hylobates moloch',
#         'asal_hewan': 'Jawa, Indonesia',
#         'tanggal_lahir': '2017-11-30',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Hutan Hujan Tropis',
#         'url_foto': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT82ZTpZW85LefM57CB17cj9xc4OWGgnRlirg&s',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a17',
#         'nama': 'Kiwi',
#         'spesies': 'Nasalis larvatus',
#         'asal_hewan': 'Kalimantan, Indonesia',
#         'tanggal_lahir': '2018-08-14',
#         'status_kesehatan': 'Observasi',
#         'nama_habitat': 'Hutan Bakau',
#         'url_foto': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Proboscis_monkey_%28Nasalis_larvatus%29_male_head.jpg/250px-Proboscis_monkey_%28Nasalis_larvatus%29_male_head.jpg',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a18',
#         'nama': 'Goku',
#         'spesies': 'Macaca nigra',
#         'asal_hewan': 'Sulawesi, Indonesia',
#         'tanggal_lahir': '2019-06-22',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Hutan Hujan Tropis',
#         'url_foto': 'https://upload.wikimedia.org/wikipedia/commons/d/d4/Crested_Black_Macaque_%28Macaca_nigra%29.jpg',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a19',
#         'nama': 'Rio',
#         'spesies': 'Paradisaea apoda',
#         'asal_hewan': 'Papua, Indonesia',
#         'tanggal_lahir': '2020-02-11',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Hutan Hujan Tropis',
#         'url_foto': 'https://upload.wikimedia.org/wikipedia/commons/c/c1/Paradisaea_apoda_-Bali_Bird_Park-5.jpg',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a20',
#         'nama': 'Blu',
#         'spesies': 'Cacatua sulphurea',
#         'asal_hewan': 'Nusa Tenggara, Indonesia',
#         'tanggal_lahir': '2017-12-15',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Hutan Hujan Tropis',
#         'url_foto': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJmV4q0-CVbdJ85zBUB3g7A1ZAoUmPX6eMeA&s',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a21',
#         'nama': 'Zazu',
#         'spesies': 'Buceros rhinoceros',
#         'asal_hewan': 'Sumatera, Indonesia',
#         'tanggal_lahir': '2019-04-26',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Hutan Hujan Tropis',
#         'url_foto': 'https://cdn.download.ams.birds.cornell.edu/api/v2/asset/220489371/900',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22',
#         'nama': 'Pipi',
#         'spesies': 'Struthio camelus',
#         'asal_hewan': 'Afrika Timur',
#         'tanggal_lahir': '2018-05-05',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Savana',
#         'url_foto': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBa_RrUO3GNAs9wh72WtwusAc8-Vsbe9aUjg&s',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a23',
#         'nama': 'Tiko',
#         'spesies': 'Ara ararauna',
#         'asal_hewan': 'Brasil, Amerika Selatan',
#         'tanggal_lahir': '2019-07-14',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Hutan Hujan Tropis',
#         'url_foto': 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Ara_ararauna_Luc_Viatour.jpg',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a24',
#         'nama': 'Kaa',
#         'spesies': 'Python reticulatus',
#         'asal_hewan': 'Indonesia',
#         'tanggal_lahir': '2017-08-29',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Hutan Hujan Tropis',
#         'url_foto': 'https://cdn.britannica.com/28/239528-050-D89C8118/reticulated-python-Malayopython-reticulatus.jpg',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a25',
#         'nama': 'Rex',
#         'spesies': 'Varanus komodoensis',
#         'asal_hewan': 'Pulau Komodo, Indonesia',
#         'tanggal_lahir': '2016-03-18',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Savana',
#         'url_foto': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/202306_Varanus_komodoensis.jpg/1200px-202306_Varanus_komodoensis.jpg',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a26',
#         'nama': 'Spike',
#         'spesies': 'Crocodylus porosus',
#         'asal_hewan': 'Indonesia',
#         'tanggal_lahir': '2015-01-10',
#         'status_kesehatan': 'Sakit',
#         'nama_habitat': 'Rawa',
#         'url_foto': 'https://reptile-database.reptarium.cz/content/photo_rd_02/Crocodylus-porosus-03000030135_01.jpg',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a27',
#         'nama': 'Crush',
#         'spesies': 'Chelonia mydas',
#         'asal_hewan': 'Indonesia',
#         'tanggal_lahir': '2010-09-22',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Terumbu Karang',
#         'url_foto': 'https://i0.wp.com/www.naturefiji.org/wp-content/uploads/2008/04/Green-turtle-Chelonia-mydas.jpg?ssl=1',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a28',
#         'nama': 'Ziggy',
#         'spesies': 'Iguana iguana',
#         'asal_hewan': 'Amerika Selatan',
#         'tanggal_lahir': '2019-11-03',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Hutan Hujan Tropis',
#         'url_foto': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Iguana_iguana.jpg/1200px-Iguana_iguana.jpg',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a29',
#         'nama': 'Dotty',
#         'spesies': 'Giraffa camelopardalis',
#         'asal_hewan': 'Kenya, Afrika',
#         'tanggal_lahir': '2017-07-21',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Savana',
#         'url_foto': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1LBOAqJBIE1mB6IX7cGkwZaH7H-ksUa5hIg&s',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a30',
#         'nama': 'Stripes',
#         'spesies': 'Equus quagga',
#         'asal_hewan': 'Tanzania, Afrika',
#         'tanggal_lahir': '2018-10-11',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Savana',
#         'url_foto': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJAFJ2cCC3gFAubQ8mFa77Oj8KFexvUJkM0A&s',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a31',
#         'nama': 'Bruno',
#         'spesies': 'Ursus arctos',
#         'asal_hewan': 'Kanada, Amerika Utara',
#         'tanggal_lahir': '2016-05-15',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Pegunungan',
#         'url_foto': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVqK1DBnGuqtHFqW6P2r7aSKsHphFk049cgA&s',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a32',
#         'nama': 'Felix',
#         'spesies': 'Panthera onca',
#         'asal_hewan': 'Brasil, Amerika Selatan',
#         'tanggal_lahir': '2018-09-07',
#         'status_kesehatan': 'Observasi',
#         'nama_habitat': 'Hutan Hujan Tropis',
#         'url_foto': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Jaguar_%28Panthera_onca_palustris%29_male_Three_Brothers_River_2_%28cropped%29.jpg/1200px-Jaguar_%28Panthera_onca_palustris%29_male_Three_Brothers_River_2_%28cropped%29.jpg',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a33',
#         'nama': 'Rocky',
#         'spesies': 'Rhinoceros unicornis',
#         'asal_hewan': 'Nepal, Asia',
#         'tanggal_lahir': '2015-12-03',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Padang Rumput',
#         'url_foto': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Indian_Rhino_%28Rhinoceros_unicornis%291_-_Relic38.jpg/2560px-Indian_Rhino_%28Rhinoceros_unicornis%291_-_Relic38.jpg',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a34',
#         'nama': 'Sandy',
#         'spesies': 'Camelus dromedarius',
#         'asal_hewan': 'Mesir, Afrika',
#         'tanggal_lahir': '2016-08-25',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Gurun',
#         'url_foto': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_svbhARlCQHlXZnDRtuEKxvFwmfIDlyaBiA&s',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a35',
#         'nama': 'Spiky',
#         'spesies': 'Hystrix cristata',
#         'asal_hewan': 'Afrika Utara',
#         'tanggal_lahir': '2019-03-16',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Gurun',
#         'url_foto': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQzJ1uAnTuxPWpaoAPQyUQwKEOh4eGuiZ4Xw&s',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a36',
#         'nama': 'Slinky',
#         'spesies': 'Uromastyx aegyptia',
#         'asal_hewan': 'Timur Tengah',
#         'tanggal_lahir': '2020-01-17',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Gurun',
#         'url_foto': 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Uromastyx_aegyptia_2.jpg',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a37',
#         'nama': 'Putih',
#         'spesies': 'Tyto alba',
#         'asal_hewan': 'Jawa, Indonesia',
#         'tanggal_lahir': '2019-02-28',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Padang Rumput',
#         'url_foto': 'https://www.asianagri.com/wp-content/uploads/2019/03/Asian_Agri_Tyto_Alba_-_Natural_Pest_Management_1.jpg',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a38',
#         'nama': 'Banteng',
#         'spesies': 'Bos javanicus',
#         'asal_hewan': 'Jawa, Indonesia',
#         'tanggal_lahir': '2017-06-14',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Padang Rumput',
#         'url_foto': 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Banteng_Alas_Purwo.jpg',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a39',
#         'nama': 'Badak',
#         'spesies': 'Rhinoceros sondaicus',
#         'asal_hewan': 'Jawa, Indonesia',
#         'tanggal_lahir': '2014-11-22',
#         'status_kesehatan': 'Observasi',
#         'nama_habitat': 'Hutan Hujan Tropis',
#         'url_foto': 'https://cdn-gonef.nitrocdn.com/UbWAxHlpDDRAfYTBoCBfYvGZgzkfyWTb/assets/images/optimized/rev-c08d0b4/seethewild.org/wp-content/uploads/2022/09/javan-rhinoceros-768x432-1.jpg',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a40',
#         'nama': 'Komo',
#         'spesies': 'Babyrousa babyrussa',
#         'asal_hewan': 'Sulawesi, Indonesia',
#         'tanggal_lahir': '2018-04-19',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Hutan Hujan Tropis',
#         'url_foto': 'https://upload.wikimedia.org/wikipedia/commons/c/cd/Hirscheber1a.jpg',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a41',
#         'nama': 'Poky',
#         'spesies': 'Echidna aculeatus',
#         'asal_hewan': 'Australia',
#         'tanggal_lahir': '2019-12-12',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Padang Rumput',
#         'url_foto': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRivds8jSfrZG4d9n1wnvAB0kz2uBsrcdrTRQ&s',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a42',
#         'nama': 'Hopper',
#         'spesies': 'Macropus rufus',
#         'asal_hewan': 'Australia',
#         'tanggal_lahir': '2018-07-30',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Padang Rumput',
#         'url_foto': 'https://upload.wikimedia.org/wikipedia/commons/f/f1/Red_kangaroo_-_melbourne_zoo.jpg',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a43',
#         'nama': 'Sleepy',
#         'spesies': 'Phascolarctos cinereus',
#         'asal_hewan': 'Australia',
#         'tanggal_lahir': '2017-05-05',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Hutan Hujan Tropis',
#         'url_foto': 'https://upload.wikimedia.org/wikipedia/commons/4/49/Koala_climbing_tree.jpg',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a44',
#         'nama': 'Bubbles',
#         'spesies': 'Tursiops truncatus',
#         'asal_hewan': 'Laut Indonesia',
#         'tanggal_lahir': '2016-09-18',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Terumbu Karang',
#         'url_foto': 'https://upload.wikimedia.org/wikipedia/commons/b/bc/Tursiops_truncatus_01-cropped.jpg',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a45',
#         'nama': 'Nemo',
#         'spesies': 'Amphiprion ocellaris',
#         'asal_hewan': 'Laut Indonesia',
#         'tanggal_lahir': '2020-03-28',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Terumbu Karang',
#         'url_foto': 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Amphiprion_ocellaris_%281%29.jpg',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a46',
#         'nama': 'Shelly',
#         'spesies': 'Eretmochelys imbricata',
#         'asal_hewan': 'Laut Indonesia',
#         'tanggal_lahir': '2015-08-07',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Terumbu Karang',
#         'url_foto': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRV4VIllNN694xVvh7hFNx5X1hOHy_W78GUOg&s',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a47',
#         'nama': 'Fleecy',
#         'spesies': 'Capra aegagrus hircus',
#         'asal_hewan': 'Pegunungan Himalaya',
#         'tanggal_lahir': '2019-01-03',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Pegunungan',
#         'url_foto': 'https://upload.wikimedia.org/wikipedia/commons/b/b2/Hausziege_04.jpg',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a48',
#         'nama': 'Snowy',
#         'spesies': 'Pantholops hodgsonii',
#         'asal_hewan': 'Tibet',
#         'tanggal_lahir': '2018-11-15',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Pegunungan',
#         'url_foto': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_hqUukI5jeYqWgzNRIp5U97VYSSJPW0C4JUSgUAcq4RvQc84OhCLuZhrq-PFnXYhQX-M&usqp=CAU',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a49',
#         'nama': 'Alpine',
#         'spesies': 'Rupicapra rupicapra',
#         'asal_hewan': 'Alpen, Eropa',
#         'tanggal_lahir': '2017-10-10',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Pegunungan',
#         'url_foto': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTzBU2KN_a9XYNdmU0U9mr9Dfbyw1MLSVwSQ&s',
#     },
#     {
#         'id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a50',
#         'nama': 'Soar',
#         'spesies': 'Aquila chrysaetos',
#         'asal_hewan': 'Amerika Utara',
#         'tanggal_lahir': '2018-06-09',
#         'status_kesehatan': 'Sehat',
#         'nama_habitat': 'Pegunungan',
#         'url_foto': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgUOt1jogkXuGdvbl3UE_AiGVrJIblB3y5BA&s',
#     },
# ]

# # CATATAN_MEDIS data
# rekam_medis_data = [
#     {
#         'id': '1',
#         'id_hewan': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
#         'tanggal_pemeriksaan': '2023-09-15',
#         'nama_dokter': 'Dr. Ajeng Pratiwi',
#         'status_kesehatan': 'Pemulihan',
#         'diagnosis': 'Infeksi kulit ringan',
#         'pengobatan': 'Antibiotik dan salep antijamur',
#         'catatan_tindak_lanjut': 'Evaluasi ulang dalam 2 minggu, pantau perkembangan luka',
#     },
#     {
#         'id': '2',
#         'id_hewan': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12',
#         'tanggal_pemeriksaan': '2023-10-03',
#         'nama_dokter': 'Dr. Budi Santoso',
#         'status_kesehatan': 'Sehat',
#         'diagnosis': 'Pemeriksaan rutin',
#         'pengobatan': 'Vitamin dan suplemen',
#         'catatan_tindak_lanjut': 'Pemeriksaan berikutnya dalam 6 bulan',
#     },
#     {
#         'id': '3',
#         'id_hewan': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a17',
#         'tanggal_pemeriksaan': '2023-11-21',
#         'nama_dokter': 'Dr. Dewi Anggraini',
#         'status_kesehatan': 'Observasi',
#         'diagnosis': 'Infeksi saluran pernapasan',
#         'pengobatan': 'Antibiotik dan terapi inhalasi',
#         'catatan_tindak_lanjut': 'Pemantauan harian selama seminggu',
#     },
#     {
#         'id': '4',
#         'id_hewan': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a26',
#         'tanggal_pemeriksaan': '2023-12-07',
#         'nama_dokter': 'Dr. Eko Prasetyo',
#         'status_kesehatan': 'Sakit',
#         'diagnosis': 'Infeksi pada kaki',
#         'pengobatan': 'Antibiotik spektrum luas dan perawatan luka',
#         'catatan_tindak_lanjut': 'Perawatan luka harian dan evaluasi ulang dalam 5 hari',
#     },
#     {
#         'id': '5',
#         'id_hewan': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a26',
#         'tanggal_pemeriksaan': '2025-04-01',
#         'nama_dokter': 'Dr. Siti Aminah',
#         'status_kesehatan': 'Sakit',
#         'diagnosis': 'Infeksi saluran pernapasan',
#         'pengobatan': 'Antibiotik selama 7 hari',
#         'catatan_tindak_lanjut': 'Evaluasi kondisi perbaikan ventilasi kandang',
#     },
#     {
#         'id': '6',
#         'id_hewan': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a32',
#         'tanggal_pemeriksaan': '2024-01-18',
#         'nama_dokter': 'Dr. Fitri Wulandari',
#         'status_kesehatan': 'Observasi',
#         'diagnosis': 'Penurunan nafsu makan',
#         'pengobatan': 'Stimulan nafsu makan dan vitamin',
#         'catatan_tindak_lanjut': 'Pantau pola makan selama 10 hari',
#     },
#     {
#         'id': '7',
#         'id_hewan': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a39',
#         'tanggal_pemeriksaan': '2024-02-05',
#         'nama_dokter': 'Dr. Gilang Ramadhan',
#         'status_kesehatan': 'Observasi',
#         'diagnosis': 'Parasit internal',
#         'pengobatan': 'Obat cacing dan probiotik',
#         'catatan_tindak_lanjut': 'Pemeriksaan feses ulang dalam 2 minggu',
#     },
#     {
#         'id': '8',
#         'id_hewan': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13',
#         'tanggal_pemeriksaan': '2024-02-22',
#         'nama_dokter': 'Dr. Hendra Wijaya',
#         'status_kesehatan': 'Sehat',
#         'diagnosis': 'Masalah gigi',
#         'pengobatan': 'Pembersihan gigi dan pengikisan',
#         'catatan_tindak_lanjut': 'Pemeriksaan gigi rutin setiap 3 bulan',
#     },
#     {
#         'id': '9',
#         'id_hewan': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a14',
#         'tanggal_pemeriksaan': '2024-03-10',
#         'nama_dokter': 'Dr. Intan Permata',
#         'status_kesehatan': 'Sehat',
#         'diagnosis': 'Vaksinasi rutin',
#         'pengobatan': 'Vaksin rabies dan distemper',
#         'catatan_tindak_lanjut': 'Vaksinasi berikutnya tahun depan',
#     },
#     {
#         'id': '10',
#         'id_hewan': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a44',
#         'tanggal_pemeriksaan': '2024-03-25',
#         'nama_dokter': 'Dr. Joko Susilo',
#         'status_kesehatan': 'Pemulihan',
#         'diagnosis': 'Lesi kulit',
#         'pengobatan': 'Pengobatan antibiotik dan terapi air',
#         'catatan_tindak_lanjut': 'Evaluasi kondisi kulit setiap 3 hari',
#     },
#     {
#         'id': '11',
#         'id_hewan': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a46',
#         'tanggal_pemeriksaan': '2024-04-12',
#         'nama_dokter': 'Dr. Kartika Sari',
#         'status_kesehatan': 'Pemulihan',
#         'diagnosis': 'Retak pada cangkang',
#         'pengobatan': 'Penutupan retak dengan resin khusus',
#         'catatan_tindak_lanjut': 'Pemantauan kesembuhan cangkang selama 4 minggu',
#     },
# ]

# # JADWAL_PEMERIKSAAN_KESEHATAN data
# # JADWAL_PEMERIKSAAN_KESEHATAN data
# jadwal_pemeriksaan_data = [
#     {
#         'id_hewan': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
#         'tgl_pemeriksaan_selanjutnya': '2024-06-15',
#         'freq_pemeriksaan_rutin': 3,
#         'nama_hewan': 'Raja',
#     },
#     {
#         'id_hewan': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12',
#         'tgl_pemeriksaan_selanjutnya': '2024-05-03',
#         'freq_pemeriksaan_rutin': 2,
#         'nama_hewan': 'Kiko',
#     },
#     {
#         'id_hewan': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13',
#         'tgl_pemeriksaan_selanjutnya': '2024-05-22',
#         'freq_pemeriksaan_rutin': 1,
#         'nama_hewan': 'Luna',
#     },
#     {
#         'id_hewan': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a14',
#         'tgl_pemeriksaan_selanjutnya': '2024-06-10',
#         'freq_pemeriksaan_rutin': 3,
#         'nama_hewan': 'Simba',
#     },
#     {
#         'id_hewan': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a17',
#         'tgl_pemeriksaan_selanjutnya': '2024-05-21',
#         'freq_pemeriksaan_rutin': 1,
#         'nama_hewan': 'Kiwi',
#     },
#     {
#         'id_hewan': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a26',
#         'tgl_pemeriksaan_selanjutnya': '2024-05-05',
#         'freq_pemeriksaan_rutin': 0.5,
#         'nama_hewan': 'Spike',
#     },
#     {
#         'id_hewan': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a32',
#         'tgl_pemeriksaan_selanjutnya': '2024-05-18',
#         'freq_pemeriksaan_rutin': 1,
#         'nama_hewan': 'Felix',
#     },
#     {
#         'id_hewan': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a39',
#         'tgl_pemeriksaan_selanjutnya': '2024-05-05',
#         'freq_pemeriksaan_rutin': 1,
#         'nama_hewan': 'Badak',
#     },
#     {
#         'id_hewan': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a44',
#         'tgl_pemeriksaan_selanjutnya': '2024-05-25',
#         'freq_pemeriksaan_rutin': 2,
#         'nama_hewan': 'Bubbles',
#     },
#     {
#         'id_hewan': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a46',
#         'tgl_pemeriksaan_selanjutnya': '2024-07-12',
#         'freq_pemeriksaan_rutin': 3,
#         'nama_hewan': 'Shelly',
#     },
# ]

# # PAKAN & MEMBERI combined data
# pemberian_pakan_data = [
#     {
#         'id': '1',
#         'id_hewan': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
#         'jenis_pakan': 'Daging Sapi',
#         'jumlah_pakan': 8,
#         'jadwal': '2024-04-25 08:00:00',
#         'status': 'Menunggu Pemberian',
#         'nama_hewan': 'Raja',
#     },
#     {
#         'id': '2',
#         'id_hewan': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12',
#         'jenis_pakan': 'Buah-buahan Segar',
#         'jumlah_pakan': 5,
#         'jadwal': '2024-04-25 09:30:00',
#         'status': 'Selesai Diberikan',
#         'nama_hewan': 'Kiko',
#     },
#     {
#         'id': '3',
#         'id_hewan': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13',
#         'jenis_pakan': 'Rumput dan Sayuran',
#         'jumlah_pakan': 25,
#         'jadwal': '2024-04-25 10:15:00',
#         'status': 'Selesai Diberikan',
#         'nama_hewan': 'Luna',
#     },
#     {
#         'id': '4',
#         'id_hewan': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a14',
#         'jenis_pakan': 'Daging Kambing',
#         'jumlah_pakan': 10,
#         'jadwal': '2024-04-26 08:30:00',
#         'status': 'Menunggu Pemberian',
#         'nama_hewan': 'Simba',
#     },
#     {
#         'id': '5',
#         'id_hewan': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a43',
#         'jenis_pakan': 'Daun Eucalyptus',
#         'jumlah_pakan': 3,
#         'jadwal': '2024-04-25 13:45:00',
#         'status': 'Menunggu Pemberian',
#         'nama_hewan': 'Sleepy',
#     },
# ]

# # Combined data for riwayat_pakan
# riwayat_pakan_data = [
#     {
#         'nama_hewan': 'Raja',
#         'spesies': 'Panthera tigris sumatrae',
#         'asal_hewan': 'Sumatera, Indonesia',
#         'tanggal_lahir': '2018-03-12',
#         'habitat': 'Hutan Hujan Tropis',
#         'status_kesehatan': 'Sehat',
#         'jenis_pakan': 'Daging Sapi',
#         'jumlah_pakan': 8,
#         'jadwal': '2024-04-25 08:00:00'
#     },
#     {
#         'nama_hewan': 'Kiko',
#         'spesies': 'Pongo pygmaeus',
#         'asal_hewan': 'Kalimantan, Indonesia',
#         'tanggal_lahir': '2016-07-23',
#         'habitat': 'Hutan Hujan Tropis',
#         'status_kesehatan': 'Sehat',
#         'jenis_pakan': 'Buah-buahan Segar',
#         'jumlah_pakan': 5,
#         'jadwal': '2024-04-25 09:30:00'
#     },
#     {
#         'nama_hewan': 'Luna',
#         'spesies': 'Elephas maximus sumatranus',
#         'asal_hewan': 'Sumatera, Indonesia',
#         'tanggal_lahir': '2014-05-17',
#         'habitat': 'Hutan Hujan Tropis',
#         'status_kesehatan': 'Sehat',
#         'jenis_pakan': 'Rumput dan Sayuran',
#         'jumlah_pakan': 25,
#         'jadwal': '2024-04-25 10:15:00'
#     },
# ]

# # List of dokter hewan
# dokter_hewan = [
#     'Dr. Ajeng Pratiwi',
#     'Dr. Budi Santoso',
#     'Dr. Dewi Anggraini',
#     'Dr. Eko Prasetyo',
#     'Dr. Fitri Wulandari',
#     'Dr. Gilang Ramadhan',
#     'Dr. Hendra Wijaya',
#     'Dr. Intan Permata',
#     'Dr. Joko Susilo',
#     'Dr. Kartika Sari',
#     'Dr. Luhur Prabowo',
#     'Dr. Mawar Indah',
#     'Dr. Nugroho Santoso',
#     'Dr. Putri Maharani',
#     'Dr. Rizky Pratama',
#     'Dr. Siti Aminah',
# ]

# # List of penjaga hewan
# penjaga_hewan = [
#     'Arya Wijaya',
#     'Bayu Pradana',
#     'Citra Lestari',
#     'Dimas Putra',
#     'Elsa Safitri',
#     'Fajar Ramadhan',
#     'Gita Purnama',
#     'Haris Kurniawan',
#     'Indra Maulana',
#     'Jasmine Putri',
# ]

# # List of habitat
# habitat_data = [
#     {
#         'nama': 'Hutan Hujan Tropis',
#         'luas_area': 5000.75,
#         'kapasitas': 120,
#         'status': 'Aktif'
#     },
#     {
#         'nama': 'Padang Rumput',
#         'luas_area': 3200.50,
#         'kapasitas': 80,
#         'status': 'Aktif'
#     },
#     {
#         'nama': 'Pegunungan',
#         'luas_area': 4500.25,
#         'kapasitas': 60,
#         'status': 'Aktif'
#     },
#     {
#         'nama': 'Rawa',
#         'luas_area': 2800.00,
#         'kapasitas': 45,
#         'status': 'Pemeliharaan'
#     },
#     {
#         'nama': 'Gurun',
#         'luas_area': 3800.50,
#         'kapasitas': 30,
#         'status': 'Aktif'
#     },
#     {
#         'nama': 'Savana',
#         'luas_area': 4200.75,
#         'kapasitas': 90,
#         'status': 'Aktif'
#     },
#     {
#         'nama': 'Terumbu Karang',
#         'luas_area': 1500.25,
#         'kapasitas': 200,
#         'status': 'Aktif'
#     },
#     {
#         'nama': 'Hutan Bakau',
#         'luas_area': 2100.50,
#         'kapasitas': 50,
#         'status': 'Renovasi'
#     },
# ]